// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchedsForums.Infrastructure.Contexts;

#nullable disable

namespace SchedsForums.Infrastructure.Migrations
{
    [DbContext(typeof(SchedsForumsDbContext))]
    [Migration("20241023103824_majors-faculties-forums-add")]
    partial class majorsfacultiesforumsadd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaseForumBaseUser", b =>
                {
                    b.Property<string>("SubscribedForumsId")
                        .HasColumnType("text");

                    b.Property<string>("SubscribedUsersId")
                        .HasColumnType("text");

                    b.HasKey("SubscribedForumsId", "SubscribedUsersId");

                    b.HasIndex("SubscribedUsersId");

                    b.ToTable("BaseForumBaseUser");
                });

            modelBuilder.Entity("ForumModerators", b =>
                {
                    b.Property<string>("ForumId")
                        .HasColumnType("text");

                    b.Property<string>("ModeratorId")
                        .HasColumnType("text");

                    b.HasKey("ForumId", "ModeratorId");

                    b.HasIndex("ModeratorId");

                    b.ToTable("ForumModerators");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Common.BaseForum", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForumType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Forums");

                    b.HasDiscriminator<string>("ForumType").HasValue("BaseForum");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Common.BaseUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("BaseUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MajorId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Faculty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Major", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacultyId")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.CourseForum", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Common.BaseForum");

                    b.Property<string>("CourseId")
                        .HasColumnType("text");

                    b.HasIndex("CourseId");

                    b.HasDiscriminator().HasValue("Course");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.FacultyForum", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Common.BaseForum");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("FacultyId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Faculty");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.GeneralForum", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Common.BaseForum");

                    b.HasDiscriminator().HasValue("General");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.MajorForum", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Common.BaseForum");

                    b.Property<string>("MajorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("MajorId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Major");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Admin", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Common.BaseUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Moderator", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Common.BaseUser");

                    b.HasDiscriminator().HasValue("Moderator");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Student", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Common.BaseUser");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("BaseForumBaseUser", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Common.BaseForum", null)
                        .WithMany()
                        .HasForeignKey("SubscribedForumsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedsForums.Domain.Entities.Common.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("SubscribedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForumModerators", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Common.BaseForum", null)
                        .WithMany()
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedsForums.Domain.Entities.Users.Moderator", null)
                        .WithMany()
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Common.BaseForum", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Common.BaseUser", "CreatedBy")
                        .WithMany("CreatedForums")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Course", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Major", null)
                        .WithMany("Courses")
                        .HasForeignKey("MajorId");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Major", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Faculty", "Faculty")
                        .WithMany("Majors")
                        .HasForeignKey("FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.CourseForum", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.FacultyForum", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Faculty", "Faculty")
                        .WithOne("FacultyForum")
                        .HasForeignKey("SchedsForums.Domain.Entities.Forums.FacultyForum", "FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.MajorForum", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Major", "Major")
                        .WithOne("MajorForum")
                        .HasForeignKey("SchedsForums.Domain.Entities.Forums.MajorForum", "MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Common.BaseUser", b =>
                {
                    b.Navigation("CreatedForums");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Faculty", b =>
                {
                    b.Navigation("FacultyForum");

                    b.Navigation("Majors");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Major", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("MajorForum");
                });
#pragma warning restore 612, 618
        }
    }
}
