// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchedsForums.Infrastructure.Contexts;

#nullable disable

namespace SchedsForums.Infrastructure.Migrations
{
    [DbContext(typeof(SchedsForumsDbContext))]
    [Migration("20241116180530_requestForum")]
    partial class requestForum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaseForumBaseUser", b =>
                {
                    b.Property<Guid>("SubscribedForumsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscribedUsersId")
                        .HasColumnType("uuid");

                    b.HasKey("SubscribedForumsId", "SubscribedUsersId");

                    b.HasIndex("SubscribedUsersId");

                    b.ToTable("ForumSubscriptions", (string)null);
                });

            modelBuilder.Entity("BaseForumModerator", b =>
                {
                    b.Property<Guid>("ModeratedForumsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModeratorsId")
                        .HasColumnType("uuid");

                    b.HasKey("ModeratedForumsId", "ModeratorsId");

                    b.HasIndex("ModeratorsId");

                    b.ToTable("ForumModerators", (string)null);
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.ForumRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ForumType")
                        .HasColumnType("integer");

                    b.Property<string[]>("Guidelines")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequestedById");

                    b.ToTable("ForumRequests");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.Common.BaseForum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForumType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string[]>("Guidelines")
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Forums");

                    b.HasDiscriminator<string>("ForumType").HasValue("BaseForum");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Common.BaseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("BaseUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.CourseForum", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Forums.Common.BaseForum");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.HasIndex("CourseId");

                    b.HasDiscriminator().HasValue("CourseForum");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.FacultyForum", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Forums.Common.BaseForum");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.HasIndex("FacultyId");

                    b.HasDiscriminator().HasValue("FacultyForum");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.GeneralForum", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Forums.Common.BaseForum");

                    b.HasDiscriminator().HasValue("GeneralForum");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.MajorForum", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Forums.Common.BaseForum");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid");

                    b.HasIndex("MajorId");

                    b.HasDiscriminator().HasValue("MajorForum");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Admin", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Users.Common.BaseUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.PendingModerator", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Users.Common.BaseUser");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StatusUpdatedById")
                        .HasColumnType("uuid");

                    b.HasIndex("StatusUpdatedById");

                    b.HasDiscriminator().HasValue("PendingModerator");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Student", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Users.Common.BaseUser");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Moderator", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Users.PendingModerator");

                    b.HasDiscriminator().HasValue("Moderator");
                });

            modelBuilder.Entity("BaseForumBaseUser", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Forums.Common.BaseForum", null)
                        .WithMany()
                        .HasForeignKey("SubscribedForumsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedsForums.Domain.Entities.Users.Common.BaseUser", null)
                        .WithMany()
                        .HasForeignKey("SubscribedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BaseForumModerator", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Forums.Common.BaseForum", null)
                        .WithMany()
                        .HasForeignKey("ModeratedForumsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedsForums.Domain.Entities.Users.Moderator", null)
                        .WithMany()
                        .HasForeignKey("ModeratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.ForumRequest", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Users.Student", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.Common.BaseForum", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Users.Common.BaseUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Major", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Faculty", "Faculty")
                        .WithMany("Majors")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.CourseForum", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.FacultyForum", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Forums.MajorForum", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.PendingModerator", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Users.Admin", "StatusUpdatedBy")
                        .WithMany()
                        .HasForeignKey("StatusUpdatedById");

                    b.Navigation("StatusUpdatedBy");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Faculty", b =>
                {
                    b.Navigation("Majors");
                });
#pragma warning restore 612, 618
        }
    }
}
