// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchedsForums.Infrastructure.Contexts;

#nullable disable

namespace SchedsForums.Infrastructure.Migrations
{
    [DbContext(typeof(SchedsForumsDbContext))]
    [Migration("20241031100520_ModeratorMigration")]
    partial class ModeratorMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchedsForums.Domain.Entities.Common.BaseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("BaseUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.ModeratorSignUpRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PendingModerators");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Admin", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Common.BaseUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Moderator", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Common.BaseUser");

                    b.Property<Guid>("ApprovedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModeratorSignUpRequestId")
                        .HasColumnType("uuid");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("ModeratorSignUpRequestId");

                    b.HasDiscriminator().HasValue("Moderator");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Student", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Common.BaseUser");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Moderator", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Users.Admin", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedsForums.Domain.Entities.ModeratorSignUpRequest", "ModeratorSignUpRequest")
                        .WithMany()
                        .HasForeignKey("ModeratorSignUpRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("ModeratorSignUpRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
