// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchedsForums.Infrastructure.Contexts;

#nullable disable

namespace SchedsForums.Infrastructure.Migrations
{
    [DbContext(typeof(SchedsForumsDbContext))]
    partial class SchedsForumsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchedsForums.Domain.Entities.Common.BaseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("BaseUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Admin", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Common.BaseUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.PendingModerator", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Common.BaseUser");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StatusUpdatedById")
                        .HasColumnType("uuid");

                    b.HasIndex("StatusUpdatedById");

                    b.HasDiscriminator().HasValue("PendingModerator");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Student", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Common.BaseUser");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.Moderator", b =>
                {
                    b.HasBaseType("SchedsForums.Domain.Entities.Users.PendingModerator");

                    b.HasDiscriminator().HasValue("Moderator");
                });

            modelBuilder.Entity("SchedsForums.Domain.Entities.Users.PendingModerator", b =>
                {
                    b.HasOne("SchedsForums.Domain.Entities.Users.Admin", "StatusUpdatedBy")
                        .WithMany()
                        .HasForeignKey("StatusUpdatedById");

                    b.Navigation("StatusUpdatedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
